site_name: Silicon Tabula 
site_author: Pindorama
copyright: Copyright &copy; 2019-2022 Pindorama<br />"Vinicius" and the Copacabana logo are copyrighted by Pindorama et Kayo Henrique (Tamboru). Ask us for permission before using.

repo_name: Projeto-Pindorama/copacabana
repo_url: https://github.com/Projeto-Pindorama/copacabana

theme:
  name: material 
  palette:
    - scheme: default
      primary: yellow
      accent: yellow 
      toggle:
        name: Obscurum
        icon: material/weather-night
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        name: Illuminatio
        icon: material/weather-sunny 
  logo: img/logo.svg
  favicon: img/vinicius.ico

markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
      use_pygments: true
      pygments_style: rrt 

plugins:
  - mkdocs-video

extra_css:
  - css/extra.css

nav:
  - Home: index.md  
  - Frequently Asked Questions: faq.md
  - Introduction:
    - I. Prologue: intro/prologue.md
    - II. Technical introdution to Pindorama/Copacabana: intro/intro.1.md 
  - From the toolchain to the 付け根 from Scratch!:
    - What I'll need?: build/what-ill-need.md
    - Laying the groundwork: build/groundwork.md 
      #    - cross-tools:
      #      - List of packages:
      #    - tools:
      #      - List of packages:
      #    - tsukene:
      #      - List of packages:
